name: Deploy to WordPress.org
on:
  workflow_dispatch:
  push:
    tags:
    - "*"
  pull_request:
    tags:
    - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: WordPress Plugin Deploy
        uses: nk-o/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
